### ISSUE TITLE
You couldn't possibly have made this more complex – Docker, seriously?

### ISSUE THREAD

**Issue by blaasvaer** [pthom/northwind_psql#20]
https://github.com/engindemirog/Northwind-Database-Script-for-Postgre-Sql

This link provides a simple .sql script that you can run on whatever PostgreSQL setup you decided on.

**Comment by pthom** [comment]
I suppose that you found that there is also a simple script in the repo.

Extract from the first lines of the Readme

> Use the provided sql file nortwhind.sql in order to populate your database.
