### ISSUE TITLE
License

### ISSUE THREAD

**Issue by dwanneruchi** [pthom/northwind_psql#3]
I think I placed this in the incorrect spot earlier: I know that the northwind dataset is available under an open source license, as is the database for SQL Server. 

I am curious if I am able to use your specific code for the creation of the postgresql DB for a course I am running in the near future? If not, no worries - I just figured you have done a great job of translating into postgreSQL and I should inquire!

**Comment by pthom** [comment]
The license is Microsoft Public License (Ms-PL) (http://northwinddatabase.codeplex.com/license) as I just translated the database from one format to the other.
