### ISSUE TITLE
use -X, --no-psqlrc  to ensure basic use of psql

### ISSUE THREAD

**Issue by homberghp** [pthom/northwind_psql#4]
Many user use a .psqlrc file, for instance to always turn auto commit off.
This is for good measure and is what I cal my safety belt against.

To make you script (create_db.sh) work in the presence of such settings, you might want to add
-X of --no-psqlrc in every call to psql.

See the text below.
Thx for your effort.

`
#!/bin/bash

dropdb northwind
dropuser northwind_user

createdb northwind
psql -X northwind < northwind.sql

psql -X  template1 -c "create user northwind_user;"
psql -X template1 -c "alter user northwind_user password 'thewindisblowing';"
psql -X template1 -c "grant all on DATABASE northwind to northwind_user;"
psql -X northwind -c "GRANT ALL on ALL tables IN SCHEMA public to northwind_user"
`

**Comment by pthom** [comment]
This is done
